#!/usr/bin/env python3
import argparse
import re
from pathlib import Path
    
parser = argparse.ArgumentParser(
                    prog='wordlesolver',
                    description='Solve wordle and derivative puzzles')

parser.add_argument('-d', '--dict', help='Dictionary to use', required=True)
parser.add_argument('-r', '--reject', help='Letters to reject', required=True)
parser.add_argument('position', help='Knowledge per position: .=unknown, ^abc=none of abc, d=exactly d', nargs='+')
args = parser.parse_args()

# Globally rejected characters, compile to regex
re_reject = re.compile(f"[{args.reject}]", re.IGNORECASE)

# If a position description starts with ^, convert it to a character class regex
for n in range(len(args.position)):
    if re.search(r'^\^', args.position[n]):
        args.position[n] = f"[{args.position[n]}]"
    args.position[n] = re.compile(args.position[n], re.IGNORECASE)

# Process the dictionary line by line
dictfilename=f"{Path(__file__).parent}/{args.dict}"
try:
    f = open(dictfilename)
except FileNotFoundError:
    print(f"Could not open {dictfilename}.")
else:
    with f:
        for line in f:
            word = line.rstrip()
            positions = len(args.position)
            # Ignore words with length other than number of positional args
            if (len(word) != positions):
                continue
            # Ignore words with globally rejected characters
            if(re.search(re_reject, word)):
                continue
            # Match each position
            for n in range(len(word)):
                if not re.search(args.position[n], list(word)[n]):
                    break
            else:
                print(word)