#!/usr/bin/env python3
import argparse
import re
import sys
from pathlib import Path
# from icecream import ic
    
parser = argparse.ArgumentParser(description='Solve wordle and derivative puzzles')

parser.add_argument('-d', '--dict', help='Dictionary to use (absolute filename, name in /usr/share/dict, name in ./dicts)', required=True)
parser.add_argument('-r', '--reject', help='Letters to globally reject', required=True)
parser.add_argument('position', help='Knowledge per position: .=unknown, ^abc=elsewhere (yellow), d=d here (green)', nargs='+')
args = parser.parse_args()

# Globally rejected characters, compile to regex
re_reject = re.compile(f"[{args.reject}]", re.IGNORECASE)

# Validate input
positionals = len(args.position)
for n in range(positionals):
    if re.search(r'^\^', args.position[n]):
        # rewrite as a negated character class
        args.position[n] = f"[{args.position[n]}]"
    elif re.search(r'..', args.position[n]):
        # Bogus position knowledge
        print("Invalid position knowledge.")
        sys.exit(1)
    elif re.search(r'^\w$', args.position[n]) and re.search(args.position[n], args.reject):
        # Edge case: Character is confirmed in one place but rejected in another
        print(f"Character {args.position[n]} is positional-confirmed but globally-rejected.")
        sys.exit(1)
    # Compile position knowledge as regex
    args.position[n] = re.compile(args.position[n], re.IGNORECASE)

# Find dictionary
if Path(args.dict).exists():
    dictfilename=args.dict 
elif Path(f"/usr/share/dict/{args.dict}").exists():
    dictfilename=f"/usr/share/dict/{args.dict}"
else:
    dictfilename=f"{Path(__file__).parent}/dicts/{args.dict}"

# Process the dictionary line by line
try:
    f = open(dictfilename)
except FileNotFoundError:
    print(f"Could not open {dictfilename}.")
else:
    with f:
        for line in f:
            word = line.rstrip()
            # Ignore words with positionals other than number of positional args
            if (len(word) != positionals):
                continue
            # Ignore words with globally rejected characters
            if(re.search(re_reject, word)):
                continue
            # Match each position
            for n in range(positionals):
                # Confirmed and elsewhere letters
                if not re.search(args.position[n], list(word)[n]):
                    break
            else:
                print(word)
