#!/usr/bin/env python3
import argparse
import re
import sys
from pathlib import Path
#from icecream import ic
    
parser = argparse.ArgumentParser(description='Solve wordle and derivative puzzles')

parser.add_argument('-d', '--dict', help='Dictionary to use (absolute filename, name in /usr/share/dict, name in ./dicts)', required=True)
parser.add_argument('-r', '--reject', help='Letters to globally reject')
parser.add_argument('position', help='Knowledge per position: .=unknown, ^abc=elsewhere (yellow), d=d here (green)', nargs='+')
args = parser.parse_args()

# Globally rejected characters, compile to regex
re_reject = re.compile(f"[{args.reject}]", re.IGNORECASE)

# Validate input, generate and precompile all regular expressions
positions = len(args.position)
elsewhere_positions = set()
position_regex = dict()
elsewhere_regex = dict()
for n in range(positions):
    if result := re.search(r'^\^(.+)', args.position[n]):
        # rewrite as a negated character class
        args.position[n] = f"[{args.position[n]}]"
        # Convert to non-negate character class
        elsewhere_regex[n] = re.compile(f"[{result.group(1)}]", re.IGNORECASE)
        elsewhere_positions.add(n)
        # Character specified as elsewhere but rejected globally
        for m in list(result.group(1)):
            if re.search(m, args.reject, re.IGNORECASE):
                print(f"Character {m} is elsewhere-confirmed but globally-rejected.")
                sys.exit(1)
    elif re.search(r'..', args.position[n]):
        # Bogus position knowledge
        print("Invalid position knowledge.")
        sys.exit(1)
    elif re.search(r'^\w$', args.position[n]) and re.search(args.position[n], args.reject):
        # Edge case: Character is confirmed in one place but rejected in another
        print(f"Character {args.position[n]} is positional-confirmed but globally-rejected.")
        sys.exit(1)
    # Compile position knowledge as regex
    position_regex[n] = re.compile(args.position[n], re.IGNORECASE)

# Find dictionary
if Path(args.dict).exists():
    dictfilename=args.dict 
elif Path(f"/usr/share/dict/{args.dict}").exists():
    dictfilename=f"/usr/share/dict/{args.dict}"
else:
    dictfilename=f"{Path(__file__).parent}/dicts/{args.dict}"

# Process the dictionary line by line
try:
    f = open(dictfilename)
except FileNotFoundError:
    print(f"Could not open {dictfilename}.")
else:
    with f:
        for line in f:
            word = line.rstrip()
            # Ignore words with length other than number of positional args
            if len(word) != positions:
                continue
            # Ignore words with globally rejected characters
            if re.search(re_reject, word):
                continue
            # Match each position
            usable=True
            for n in range(positions):
                # Confirmed letter is in the known position, or elsewhere letter is absent
                if not re.search(position_regex[n], list(word)[n]):
                    usable=False
            if usable==False:
                continue
            # Elsewhere letters must all be present somewhere else in the word
            # There still is an edge case here, I think if a letter is rejected
            #   twice that's in the word twice, or something
            usable = 0
            for n in elsewhere_positions:
                if re.search(elsewhere_regex[n], word):
                    usable += 1
            if usable != len(elsewhere_positions):
                continue
            # Still here?
            print(word)
